# Generated by Django 4.1 on 2024-11-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction", name="slug", field=models.SlugField(),
        ),
    ]
