# Generated by Django 4.1 on 2024-11-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auction_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="banner",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
