# Generated by Django 4.1 on 2024-11-13 00:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auctions", "0004_auction_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionItem",
            fields=[
                ("itemId", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("picture", models.ImageField(upload_to="media")),
                ("starting_bid", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "current_bid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Auction",),
    ]
