# Generated by Django 4.1 on 2024-11-13 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_auctionitem_itemid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
