# Generated by Django 4.1 on 2024-11-13 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auctions", "0007_auctionitem_active_alter_auctionitem_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctionItems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
