# Generated by Django 4.1 on 2024-11-14 00:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auctionitem_highestbidder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="starting_bid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
