# Generated by Django 5.1.3 on 2024-11-20 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_auctionitem_starting_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="time_left",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
