# Generated by Django 5.1.3 on 2024-11-20 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_auctionitem_time_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="time_left",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
