# Generated by Django 5.1.3 on 2024-12-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_notifications"),
    ]

    operations = [
        migrations.DeleteModel(name="Notifications",),
    ]
